application:
  name: crudjava
  version: 1.0.0

server:
  port: 10001

#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3307/mudi
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: sa
#        password:
#    jpa:
##        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#            ddl-auto: update
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5Dialect
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    url: jdbc:h2:file:/home/wolmir/dbh2teset
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update